"""question name and timestamp default

Revision ID: 255ca2db86ba
Revises: 3283dff1a531
Create Date: 2019-12-26 11:44:22.184525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '255ca2db86ba'
down_revision = '3283dff1a531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('name', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'name')
    # ### end Alembic commands ###
